### ISSUE TITLE
Energy Monitor Home Assistant 

### ISSUE THREAD

**Issue by Alfagek** [TimSoethout/goodwe-sems-home-assistant#37] opened 2021-08-04 14:59 UTC
Hey Tim,

First a big thank you for making this. I’m using it almost a year and it’s working great. 

But I have a question. Home Assistant has a new Energy monitor (2021.8). And I’m using your setup to get all things that I want in Home Assistant. But i don’t see my power return in this Energy monitor. I do have it as a entity. 

Do you know how I can get this now to use it in the new Home Assistant Energy Monitor. 
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Thanks in advance,
Marco

**Comment by kolossboss** [comment] 2021-08-04 15:11
Hi have the same question. Its all sensors are not shown in the energy configuration panel.

I think I have to include a last_reset property. But I'm not sure how to do this.

**Comment by Alfagek** [comment] 2021-08-04 16:53
Thanks for trying @kolossboss . There should probably more people who have this “problem” we will wait (and Google in the mean time)

**Comment by TimSoethout** [comment] 2021-08-04 17:04
Yes let's try to get this working. Not sure about the reset time, but maybe
the API also shows kWh this year and we can use start of current year for
this.

**Comment by kolossboss** [comment] 2021-08-04 17:32
Hi,
I now created a template sensor with `total_buy`

```
- platform: template
  sensors:
    pv_buy_total:
      value_template: "{{ states.sensor.sems_portal.attributes.total_buy }}"
      unit_of_measurement: "kWh"
      friendly_name: "PV kWh gekauft Total"
```

An created a Utility Meter Sensor and cycle daily

```
utility_meter:
  energy_buy_daily_test:
    source: sensor.pv_buy_total
    cycle: daily
```

Added a few missing attributes to `sensor.energy_buy_daily_test` in the customize.yaml

```
sensor.energy_buy_daily_test:
  unit_of_measurement: kWh
  device_class: energy
```

Now the sensor is detected by the Energy Management configuration. But I'm not sure if its working, because I'm not receiving any data at this moment (house ins running on battery)

**Comment by Alfagek** [comment] 2021-08-04 18:30
I did try to add the device class to my configuration.yaml (pv-etoday) but it’s not showing up in my energy monitor. 

@kolossboss, maybe it’s not showing up yet, because it’s a daily sensor that you are creating. And what i know it will add the value on 00:00 daily

**Comment by kolossboss** [comment] 2021-08-04 18:38
Hi my sensor is now working. The house Battery is empty and the Inverter is now buying from grid.
<img width="1006" alt="Bildschirmfoto 2021-08-04 um 20 31 24" src="https://user-images.githubusercontent.com/11015086/128235845-97920206-b377-4e88-9cd1-22ccbcc26244.png">

They problem with your sensor is, its a template sensor, and template sensors are not supported. (quote from frenck from HA)
You need to create a utility_meter sensor as I wrote above

**Comment by spudje** [comment] 2021-08-04 18:41
I do hope as well changes will be made to this component to make it work with Hass Energy. I'd rather not create a utility meter, because in essence you'll have two utility meters. The one you create with the utility meter integration and the new Energy Management feature, which is a utility meter in itself.

**Comment by matthewbayard** [comment] 2021-08-05 05:17
Still cant see my PV production in Energy section. Anybody got it working?

**Comment by conormce** [comment] 2021-08-05 13:20
Just got my first values showing up on the Energy dashboard, followed @kolossboss method of adding a utility meter sensor   with the source of daily production total and then after a restart I customised that sensors device_class and unit of measurement. 
It looks to me like the energy dashboard assumes it's source is a daily total measurement and it uses the difference between the two most recent values.

**Comment by TimSoethout** [comment] 2021-08-05 14:41
I added an extra sensor for total kWh in a branch. It is released as `3.3.0-beta`. (go to HACS > Integrations > Search SEMS > reinstall > show beta versions)

It does not yet show up for me in the dashboard, but I'll wait an hour and see what happens.

**Comment by tabnul** [comment] 2021-08-05 14:47
> 3.3.0-beta

Great news, i was allready messing around with the sensors.. installing the beta -now-  ;)

**Comment by tabnul** [comment] 2021-08-05 14:53
sensor is existent now.
unable to choose it as input for solar panels. i would expect that that would be visible immediately (apart from the statistics)

![image](https://user-images.githubusercontent.com/16493960/128371303-946b89a9-d7eb-4d89-bb84-46e5fbb505c1.png)

**Comment by Alfagek** [comment] 2021-08-05 14:55
> I added an extra sensor for total kWh in a branch. It is released as `3.3.0-beta`. (go to HACS > Integrations > Search SEMS > reinstall > show beta versions)
> 
> It does not yet show up for me in the dashboard, but I'll wait an hour and see what happens.

@TimSoethout 
Also installed Beta version. But the sensor isn’t showing up in the list. I do see a extra entitie at the goodwe intergratie.

**Comment by conormce** [comment] 2021-08-05 14:56
Just tested and the same as @tabnul above, I was able to get it to show up by 
* going to Developer Tools->States
* Select "sensor.inverter_home_energy"
* Adding the following to state attributes
"state_class: measurement
last_reset: '2021-08-05T11:27:42.998420+00:00'

It'll take around one hour before I can tell if it matches the output from the utility meter option

**Comment by TimSoethout** [comment] 2021-08-05 14:56
I'm having the same. It's not showing in the list of the power manager. I am hoping it will turn up after a while as @conormce was saying: "It looks like you need a full hours data from the sensor before it turns up."

Does anyone know how to check if statistics are working?

**Comment by TimSoethout** [comment] 2021-08-05 14:58
The source contains:
```
    @property
    def last_reset(self):
        """Last reset property, used by Metered entities / Long Term Statistics"""
        return homeassistant.util.dt.utc_from_timestamp(0)

    @property
    def state_class(self):
        """used by Metered entities / Long Term Statistics"""
        return STATE_CLASS_MEASUREMENT
```
Apparently that is not enough to add those state attributes?

I need to make diner now and will check later tonight again.

**Comment by Alfagek** [comment] 2021-08-05 15:03
> 
> I need to make diner now and will check later tonight again.
> 
> EDIT: Probably have to add `@property def extra_state_attributes(self):` in the code.

will wait, thanks for now. Have a nice meal!

**Comment by TimSoethout** [comment] 2021-08-05 18:33
https://github.com/TimSoethout/goodwe-sems-home-assistant/releases/tag/3.3.0-beta3

This seems to work and I can select it in the Energy config!

**Comment by Dehler2** [comment] 2021-08-05 18:37
Yup, working here as well. Thanks @TimSoethout !

**Comment by TheGabeMan** [comment] 2021-08-05 18:40
Working here as well. Just a question, should I add "Inverter GoodWe Energy" to both the "Solar Panel" section and the "Return to grid" section?

**Comment by TimSoethout** [comment] 2021-08-05 18:43
@TheGabeMan , I guess only "Solar" because the kWh it shows what is produced by the panels, before any consumption in my house. Only left over usage inside goed back to grid. 
(At least for my setup.)

**Comment by TheGabeMan** [comment] 2021-08-05 18:43
@TimSoethout ah and then the "Return to grid" should probably come from my P1 monitoring devcie.

**Comment by Alfagek** [comment] 2021-08-05 18:49
@TimSoethout , awesome job. Thanks for the quick fix (y)

**Comment by tyz** [comment] 2021-08-05 18:58
Works for me as well. Tnx!! Now I only have to wait for the sun to see it in action.. 😀

**Comment by tabnul** [comment] 2021-08-05 18:59
> @TimSoethout ah and then the "Return to grid" should probably come from my P1 monitoring devcie.

exactly, p1 / meter does that part
tomorrow first day with full fletched dashboard. a bit upgrade to my old DSMR Reader setup that did not show the actual solar output and prediction (basically not able to automate against it)

Confirmed that beta 3 fixes it indeed. great work!

**Comment by TheGabeMan** [comment] 2021-08-06 05:59
It is now 7:48am down here and my GoodWe sensor (sensor.pv_outputpower) is showing 260W output, but the Energy dashboard remains empty for the solar panel section. 

In the developer tools, the "sensor.inverter_goodwe" shows a value of 260 and the attribute outputpower: 260.

**Comment by tabnul** [comment] 2021-08-06 06:04
> It is now 7:48am down here and my GoodWe sensor (sensor.pv_outputpower) is showing 260W output, but the Energy dashboard remains empty for the solar panel section.
> 
> In the developer tools, the "sensor.inverter_goodwe" shows a value of 260 and the attribute outputpower: 260.

i think this is one of the major downsides of this dashboard. data lags behind massively. it calculates per hour.
i wonder whether you can also modify this dashboard, or use it as a template for a custom energy board.

**Comment by TimSoethout** [comment] 2021-08-06 06:06
For me it starts to do something: 
<img width="277" alt="Screen Shot 2021-08-06 at 08 03 00" src="https://user-images.githubusercontent.com/593132/128463687-12e36186-4910-49cd-8bc0-b6fc74c243a4.png">
A small bullet from PV to Grid somehow, although it should go to the house I guess. I will see if it shows more when an hour is passed.

It could also be that kWh (with one digit after comma) is not precise enough. Then we'll have to use another metric. Or use the "today" value instead of the total ever kWh or something.

**Comment by TheGabeMan** [comment] 2021-08-06 06:18
As it is raining cats and dogs in Maastricht, I think I have to wait more than an hour :-)

**Comment by kevinvugts** [comment] 2021-08-06 06:40
@TimSoethout when do you plan to make a release instead of a beta?

**Comment by JornMich** [comment] 2021-08-06 07:12
> For me it starts to do something:
> <img alt="Screen Shot 2021-08-06 at 08 03 00" width="277" src="https://user-images.githubusercontent.com/593132/128463687-12e36186-4910-49cd-8bc0-b6fc74c243a4.png">
> A small bullet from PV to Grid somehow, although it should go to the house I guess. I will see if it shows more when an hour is passed.
> 
> It could also be that kWh (with one digit after comma) is not precise enough. Then we'll have to use another metric. Or use the "today" value instead of the total ever kWh or something.

It's still on 0 here, even though the entity itself seems to be updated. No bullets going from Solar to anywhere either.

**Comment by tabnul** [comment] 2021-08-06 07:17
> As it is raining cats and dogs in Maastricht, I think I have to wait more than an hour :-)

doesn't sound good for your solar panels ;)

> > For me it starts to do something:
> > <img alt="Screen Shot 2021-08-06 at 08 03 00" width="277" src="https://user-images.githubusercontent.com/593132/128463687-12e36186-4910-49cd-8bc0-b6fc74c243a4.png">
> > A small bullet from PV to Grid somehow, although it should go to the house I guess. I will see if it shows more when an hour is passed.
> > It could also be that kWh (with one digit after comma) is not precise enough. Then we'll have to use another metric. Or use the "today" value instead of the total ever kWh or something.
> 
> It's still on 0 here, even though the entity itself seems to be updated. No bullets going from Solar to anywhere either.

it will take 1-2 hours to show data
you also need to configure the new energy sensory in the energy configuration (solar)

mine works; 
![image](https://user-images.githubusercontent.com/16493960/128471864-ac8f200c-976e-4d13-b100-2537e5ee43c5.png)

**Comment by JornMich** [comment] 2021-08-06 07:24
> you also need to configure the new energy sensory in the energy configuration (solar)

And here I was, thinking I've been patient enough.. Indeed it is working now! Great stuff.

**Comment by JornMich** [comment] 2021-08-06 07:24
> > As it is raining cats and dogs in Maastricht, I think I have to wait more than an hour :-)
> 
> doesn't sound good for your solar panels ;)
> 
> > > For me it starts to do something:
> > > <img alt="Screen Shot 2021-08-06 at 08 03 00" width="277" src="https://user-images.githubusercontent.com/593132/128463687-12e36186-4910-49cd-8bc0-b6fc74c243a4.png">
> > > A small bullet from PV to Grid somehow, although it should go to the house I guess. I will see if it shows more when an hour is passed.
> > > It could also be that kWh (with one digit after comma) is not precise enough. Then we'll have to use another metric. Or use the "today" value instead of the total ever kWh or something.
> > 
> > 
> > It's still on 0 here, even though the entity itself seems to be updated. No bullets going from Solar to anywhere either.
> 
> it will take 1-2 hours to show data
> you also need to configure the new energy sensory in the energy configuration (solar)
> 
> mine works;
> ![image](https://user-images.githubusercontent.com/16493960/128471864-ac8f200c-976e-4d13-b100-2537e5ee43c5.png)

And here I was, thinking I've been patient enough.. Indeed it is working now! Great stuff.

**Comment by TimSoethout** [comment] 2021-08-06 09:13
I think the Energy tab shows the total kWh (kW *times* hour) produces on the current whole day. If you have 0.6 kW *power* for 1 hour, you produce 0.6 kWh *energy* in total.

I am glad it seems to work. I guess we can promote it to a non-beta version.

**Comment by TimSoethout** [comment] 2021-08-06 09:14
Released as 3.3.0. :D

**Closed by TimSoethout** 2021-08-06 09:14 UTC

**Comment by kevinvugts** [comment] 2021-08-06 10:28
> Released as 3.3.0. :D
> Thanks all for the input and testing.

@TimSoethout it doesn't seem to working correctly yet. My SEMS is registering a different output / capacity than the energy dashboard is showing. 

Any idea why so?

![IMG_7428](https://user-images.githubusercontent.com/17518874/128497218-649213db-0f1a-49e8-9a76-bc7ee953cb5c.PNG)
![IMG_7427](https://user-images.githubusercontent.com/17518874/128497230-8e41ea1f-0c60-4ac0-b91f-d93e2ef0eed1.PNG)

**Comment by TimSoethout** [comment] 2021-08-06 10:50
@kevinvugts, I don't know. You mean that the 3.8 kWh from the energy overview differs from the PV Energy Day of 7.5 kWh?

Maybe it is related to the delay (1/2 hours) in statistics that was mentioned earlier?
We can check this by comparing the numbers again 2 hours after sun down.

**Comment by conormce** [comment] 2021-08-06 11:09
@kevinvugts 
There are two things that can create a difference between what is showed in the energy dashboard and what is returned from the API
1) The energy dashboard is time delayed. It aggregates data by the hour and only shows it in the dashboard after that hour has completed + some time for the sensor to update. So far for me it updates ~10 minutes after the hour(
2) The energy dashboard only starts it's calculations after you add the sensor to it. I think it also only does this for "good" hours, hours where it has measurements before, during and after

I would think a combination of the two could be affecting you, 1) the current hours production will be the highest since it is approaching peak sun so the inverters total will be adding up but the dashboard won't change until 10 past the hour. 2) all the solar energy generated before you added the sensor to the dashboard won't count

**Comment by HCookie** [comment] 2021-08-09 04:38
After waiting over 2 hours, still nothing is showing up in the new energy dashboard,
One strange characteristic of the selected sensor, is that it is the total energy produced, total. No other sensor can even be selected.
Is this the right one to use, or am I missing something?
I also don't seem to get any other sensors from the panels, just current production and total.

**Comment by TimSoethout** [comment] 2021-08-09 08:33
Hi. HA takes care of tracking total per day from total kWh value.
The current output sensor contains other attributes as well. See readme in
how to get them as seperate sensors.

**Comment by HCookie** [comment] 2021-08-09 08:57
Hi,
Thanks for the assistance, and reminder to read the readme, 
I'm new to homeassistant and even more so to custom integrations,
So I appreciate the help

**Comment by TimSoethout** [comment] 2021-08-14 08:08
> To confirm, to use the new energy dashboard, `eday` or `etotal` is to be used?

I guess the component uses `etotal` internally,  but you have to select nothing yourself.

**Comment by conormce** [comment] 2021-08-14 10:19
Definitely etotal. 
eday can be reset if you adjust time on the inverter along with some other features. Also if you lose connection late in the evening which is common for me, eday resets at midnight so you lose whatever generation happened. 
etotal gets around all these issues.

**Comment by TPochobradsky** [comment] 2021-08-18 16:08
Hi guys,
could you help me with setting of Energy dashboard? I have use sensor "sensor.inverter_gw5k_et_energy" as a "Solar production", it works well. But there are not any next sensor for "Grid consumption" and "Return to grid". It seems that the negative part of "sensor.pv_excess' can be "Grid consumption" and positive part "Return to grid". Any idea how to split and display the sensor in Energy dashboard?
Thanks advance.
![image](https://user-images.githubusercontent.com/77235388/129932964-c2c0b70d-1b06-427a-babf-b43a0c075409.png)

**Comment by TimSoethout** [comment] 2021-08-18 19:20
> Hi guys,
> could you help me with setting of Energy dashboard? I have use sensor "sensor.inverter_gw5k_et_energy" as a "Solar production", it works well. But there are not any next sensor for "Grid consumption" and "Return to grid". It seems that the negative part of "sensor.pv_excess' can be "Grid consumption" and positive part "Return to grid". Any idea how to split and display the sensor in Energy dashboard?
> Thanks advance.
> ![image](https://user-images.githubusercontent.com/77235388/129932964-c2c0b70d-1b06-427a-babf-b43a0c075409.png)

Hi, I guess you need another component for this that tracks your power taken and returned from/to the grid. You fill them in separately on the first screen of the Energy Monitor. For me this data comes from a `dsmr` entity.
Maybe the buy/sell as discussed in #43 can also be used for this?

**Comment by TPochobradsky** [comment] 2021-08-18 22:26
Hi,
I have added sensors Buy and Seller. In "HA --> Settings --> Customize --> search for a Sensor" added Measurement "1970-01-01T00:00:00+00:00" and "device_class: energy". Now I see these two new sensor in Energy dashboard. Thank you it is perfekt. 
![image](https://user-images.githubusercontent.com/77235388/129980059-e42d3bef-7dc0-4c4a-9bce-8645f7745dc3.png)
Tomorow I will see if all works well.
![image](https://user-images.githubusercontent.com/77235388/129980094-f5b2725c-b130-40af-a702-5d869bce6326.png)

**Comment by dmshimself** [comment] 2021-08-18 23:17
I thought that templated sensors (such as  buy) were not currently supported by the energy component of HA.  I hope to be wrong in a good way :-)

**Comment by TPochobradsky** [comment] 2021-08-19 15:28
it looks like it works :-)
![image](https://user-images.githubusercontent.com/77235388/130096877-4f415799-7633-4c26-8b25-bba472005abe.png)

**Comment by dmshimself** [comment] 2021-08-20 05:04
yes here too.  The combination of utility meter and adding those extra atrributes seems to do the trick very nicely  :-)

**Comment by TPochobradsky** [comment] 2021-09-07 09:12
I have little bit investigated data of sensors (Buy and Seller) and it seems that problem can be in real time of resetting. Last measurement I have at 23:45:50 (0,54 kWh) and first at 00:00:50 (0 kWh). Do you know how to move first measurement to midnight?

**Comment by TPochobradsky** [comment] 2021-09-09 09:55
It seems that my problem is solved by changing of sensor state_class from "measurement" to "total_increasing". :-)

**Comment by TimSoethout** [comment] 2021-09-09 10:39
Aha, good! The latest version 3.4.0 should also fix it then, since it has the same change.
