### ISSUE TITLE
Import data inconsistent

### ISSUE THREAD

**Issue by justinmaiuto** [TimSoethout/goodwe-sems-home-assistant#109] opened 2024-06-15 11:07 UTC
Energy import consistency seems to have degraded over the last few days. Screenshot shows typical data capture for the last week, but on the 13/06 something looks to have changed and import readings are low and not linear as expected. This is not reflective of actual consumption, verified by other power monitoring device and also in the SEMS portal/app itself both showing data as expected. Could be an issue on the SEMS server/API side, but putting it here in case it could be something on the data feed/reads on HA side that changed?

![image](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/8307789/29d8d5e1-1a55-4553-918f-44e3227109ed)

**Comment by skreza** [comment] 2024-06-16 12:53
I'm seeing this same issue, however looking at data in SEMS web portal looks correct.
It's almost like it's failing to connect to SEMS to pull the data in.

![image](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/13235835/8e547de6-94ce-48ff-a989-d7b8c069be90)

**Comment by TimSoethout** [comment] 2024-06-16 13:27
It seems to reset at midnight. Maybe some auto increment setting in the component HA is missing?
Unfortunately I can't reproduce, since my inverter does not import.

**Comment by rmartinsgr** [comment] 2024-06-16 19:06
Hi,
Same issue here.
The issue has to be in the SEMS API because even there, at the end of the day you can't see the total buy amount of Kwh, only in the next day.
But it shows the realtime consumption, it's strange and in my case it stopped working on 10/06/2024 @23:00..
Don't know what to do next, a lot of automations depend on this because Homekit hk1000 only gives information by cloud API...

![image](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/70020117/bdd87c52-e07c-4fbc-b272-6d27c18d0640)

**Comment by justinmaiuto** [comment] 2024-06-16 19:19
> It seems to reset at midnight. Maybe some auto increment setting in the component HA is missing? Unfortunately I can't reproduce, since my inverter does not import.

Resetting at midnight is expected. It's the incorrect/inconsistent data feed/capture you can see from the 13/06 that is the problem it seems

**Comment by davidsonimagerygmailcom** [comment] 2024-06-17 01:29
I am seeing the same issue ... kwh metrics are all skeweed and frozen ... until a day or two later (or sometiunes much later in the day) it suddenly catches up.  I can see the issue happening in Sems portal too, it's not HA.

It all started around 13/14th June.
I"ve raised a case with my solar installer, that's gone nowhere. 

![Capture](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/540d3377-0bc4-4df3-9384-fa77f89cbb61)

Can gaurantee that overnight sometime it will magically update (and goodwe will point to that saying "all looks fine")... but all the wrong data will be ingested by HA then.

**Comment by davidsonimagerygmailcom** [comment] 2024-06-17 01:31
> I'm seeing this same issue, however looking at data in SEMS web portal looks correct. It's almost like it's failing to connect to SEMS to pull the data in.
> 
> ![image](https://private-user-images.githubusercontent.com/13235835/340101883-8e547de6-94ce-48ff-a989-d7b8c069be90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODc3ODUsIm5iZiI6MTcxODU4NzQ4NSwicGF0aCI6Ii8xMzIzNTgzNS8zNDAxMDE4ODMtOGU1NDdkZTYtOTRjZS00OGZmLWE5ODktZDdiOGMwNjliZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAxMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMzBmNWRiOTFhYzE5YmJhY2Q1ODJkYmQzYTZjNmMyOThjYmFlMDYzNTViZWZjYjM4MGUwNjdlNGI1ZDgwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwtXuGoHcKj2mGpTKg6ULOkudAYtaX4Q4bZVGY0pc5k)

Nah the data is wrong in Sems too ... untill 12-24hrs later, then suddenly it backdates the earlier days to correct figures.

I wish my home had only used 0.5kwh by the time the run rises in morning here winter! :)

**Comment by davidsonimagerygmailcom** [comment] 2024-06-18 07:57
Issue persists.  Apparently the issue is with the way the HK1000 (goodwe smart meter) and SemsPortal are talking.  Ergo, it's not an acute issue but a cloud / semsportal one.

**Comment by justinmaiuto** [comment] 2024-06-18 08:13
> Issue persists. Apparently the issue is with the way the HK1000 (goodwe smart meter) and SemsPortal are talking. Ergo, it's not an acute issue but a cloud / semsportal one.

do you have a ticker or something we could track with GoodWe on this?

**Comment by davidsonimagerygmailcom** [comment] 2024-06-18 08:24
Not really, I had raised a case with my Solar Provider here in WA (who are great) , they had logged a case with Goodwe.  Goodwe had said (after 5 days) that there's no issue (i've since seen screenshot of the conversation, the issue is goodwe not comprehending what was even written).   I've provided further screenshots and now they advised "_We are facing Eotal problem with HK1000.  Our Sems Team is trying their best to resolve this problem.   Once the bug fix we will let you know"_

At no point has anyone given me any ticket number, my solar provider is just emailing with them (under their vendor relationship I imagine).

I can see some guys on Facebook (croatia) reporting similiar.
What I do know is that when the midnight rollover happens, the previous days metrics magically are OK ... that's of little use to us.

I also make a point of not mentioning HA or pulling data into other sources because they straight out don't care or comprehend that (hence the double dip at midnight thing they couldn't comprehend earlier this year) ... or worse, they blame it.

**Comment by davidsonimagerygmailcom** [comment] 2024-06-19 08:27
Today's data looking good.  Haven't said anything back to vendor though , let's see how a couple days goes.

**Comment by rmartinsgr** [comment] 2024-06-19 10:30
> days goes.

Same, seems to be back to normal

**Comment by TimSoethout** [comment] 2024-06-19 15:17
Hooray. I will close the issue then. Please re-open if we need to do anything on this again.

**Closed by TimSoethout** 2024-06-19 15:17 UTC

**Comment by AgentKith** [comment] 2024-06-20 01:01
> Hooray. I will close the issue then. Please re-open if we need to do anything on this again.

Side question. Assuming if the WeWork API supports this, is it possible to introduce a HA service call to refresh retrospective data so they're accurate? i.e. go into the cloud and update the wrong days (while they're still being kept).
